language: go
go_import_path: github.com/kevinburke/expectedruns

os: linux
dist: trusty
sudo: false

before_script:
  - go get ./...

script:
  - make test

go:
  - 1.10.x
  - master

cache:
  directories:
    - $GOPATH/pkg
