application: expectedruns
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /humans.txt
  static_files: humans.txt
  upload: humans.txt
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /js
  static_dir: js
- url: /.*
  script: _go_app
